### ISSUE TITLE
cleanup process after run image created

### ISSUE THREAD

**Issue by finndo77** [IncredibleHolg/OverviewerDocker#2]
Hi, thanks for figuring this out, I found your repo from the issue page on [overviewer's git page](https://github.com/overviewer/Minecraft-Overviewer/issues/1595) from july 2019 about the python version mismatch.

I noticed after running the create-buildimage script and the create-docker-run scripts I ended up with 6 new docker images, is it possible to have the create-docker-run script clean up the unneeded images?

2 of the created images have no repo and no tags, I'll be mighty confused in a couple of weeks as to what they are :)

REPOSITORY|TAG|IMAGE ID|CREATED|SIZE
---|---|---|---|---
incredibleholg/mc-overview|19.10|5e13a16531b2|2 minutes ago|556MB
mc-overview|19.10|5e13a16531b2|2 minutes ago|556MB
incredibleholg/mc-overview-run|19.10|c0d3bd26ed31|3 minutes ago|261MB
mc-overview-run|19.10|c0d3bd26ed31|3 minutes ago|261MB
&lt;none>|&lt;none>|7b6516f1cbbc|3 minutes ago|195MB
&lt;none>|&lt;none>|8f718e4afef6|4 minutes ago|96.6MB

Would I be safe in saying that the 3rd entry "mc-overviewer-run" is the only necessary image file?  OR is the container dependent on more than one?

Thanks again for your work

**Comment by IncredibleHolg** [comment]
@finndo77 This project is more or less the WIP of my own Docker environment experiments.
Perhaps have a look at https://github.com/mide/minecraft-overviewer thir project is well maintained.
On the other hand: feel free to clone this one and be so kind to send me a pull request if you improve the software.

I worked on this when my Linux system was too old to have the proper Python version. Since I upgraded this project got no more updates. 

All you need to keep is one "mc-overview-run" image and one "mc-overview" image. If you look at the ID, the full tagged ones have the same ID, so not consuming any disk space.
